/**
Author: Tirth Nagar
Date: 7/12/2020
Purpose: To create the JFrame form that will ask the user what grade they are in
 */

package EducationLy;

import java.awt.Dimension;
import java.awt.Toolkit;

public class GradeSelect extends javax.swing.JFrame {

    /**
     * Creates new form GradeSelect and all of its components
     */
    public GradeSelect() {
        initComponents();
        SetIcon();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        // Determine the new location of the window
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (dim.width-w)/2;
        int y = (dim.height-h)/2;

        // Move the window
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RootWindow = new javax.swing.JPanel();
        Grade10 = new javax.swing.JButton();
        Grade9 = new javax.swing.JButton();
        Grade11 = new javax.swing.JButton();
        Grade12 = new javax.swing.JButton();
        happyPeople_img = new javax.swing.JLabel();
        titleLogo_img = new javax.swing.JLabel();
        brainCartoon_img = new javax.swing.JLabel();
        studentGrad_img = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        HowToUse = new javax.swing.JMenuItem();
        AboutUs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Education.Ly");
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 500));

        RootWindow.setBackground(new java.awt.Color(255, 255, 255));
        RootWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Grade10.setBackground(new java.awt.Color(255, 255, 255));
        Grade10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Grade10.setText("Grade 10");

        Grade9.setBackground(new java.awt.Color(255, 255, 255));
        Grade9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Grade9.setText("Grade 9");
        Grade9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grade9ActionPerformed(evt);
            }
        });

        Grade11.setBackground(new java.awt.Color(255, 255, 255));
        Grade11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Grade11.setText("Grade 11");

        Grade12.setBackground(new java.awt.Color(255, 255, 255));
        Grade12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Grade12.setText("Grade 12");

        happyPeople_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EducationLy/Images/happyPeople.jpg"))); // NOI18N

        titleLogo_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EducationLy/Images/titleLogo.png"))); // NOI18N

        brainCartoon_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EducationLy/Images/brainCartoon.png"))); // NOI18N

        studentGrad_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EducationLy/Images/studentGrad.png"))); // NOI18N

        javax.swing.GroupLayout RootWindowLayout = new javax.swing.GroupLayout(RootWindow);
        RootWindow.setLayout(RootWindowLayout);
        RootWindowLayout.setHorizontalGroup(
            RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RootWindowLayout.createSequentialGroup()
                .addGroup(RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RootWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Grade9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(Grade11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RootWindowLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Grade10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RootWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentGrad_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titleLogo_img)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brainCartoon_img, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RootWindowLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Grade12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(RootWindowLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(happyPeople_img)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RootWindowLayout.setVerticalGroup(
            RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RootWindowLayout.createSequentialGroup()
                .addGroup(RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RootWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(brainCartoon_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RootWindowLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(titleLogo_img))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RootWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(studentGrad_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grade12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RootWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Grade11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Grade9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(happyPeople_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        File.setText("File");

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        File.add(exit);

        jMenuBar1.add(File);

        Help.setText("Help");

        HowToUse.setText("How To USe");
        HowToUse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToUseActionPerformed(evt);
            }
        });
        Help.add(HowToUse);

        jMenuBar1.add(Help);

        AboutUs.setText("About Us");
        AboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutUsMouseClicked(evt);
            }
        });
        jMenuBar1.add(AboutUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RootWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //If you close the program terminate it completely
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    //When the How to use menu item is clicked teach the user how to use the program
    private void HowToUseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToUseActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this,"1. Choose Your Grade\n2. Select Your Subject\n3. Choose the Topic You Want to Learn");
    }//GEN-LAST:event_HowToUseActionPerformed

    //When the about us tab on the menu bar is clicked tell the ueser about the purpose of the program and who made it
    private void AboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutUsMouseClicked
        javax.swing.JOptionPane.showMessageDialog(this,"This GUI application is made by Education.Ly using Java.\nIts purpose is to help educate students in our community.");
    }//GEN-LAST:event_AboutUsMouseClicked

    // //When the grade 9 button is clicked make the current frame invisible and set the SubjectSelect frame visible
    private void Grade9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grade9ActionPerformed
        new SubjectSelect().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Grade9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu AboutUs;
    private javax.swing.JMenu File;
    private javax.swing.JButton Grade10;
    private javax.swing.JButton Grade11;
    private javax.swing.JButton Grade12;
    private javax.swing.JButton Grade9;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem HowToUse;
    private javax.swing.JPanel RootWindow;
    private javax.swing.JLabel brainCartoon_img;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel happyPeople_img;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel studentGrad_img;
    private javax.swing.JLabel titleLogo_img;
    // End of variables declaration//GEN-END:variables
    
    //Set the icon for the JFrame form
    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Images//study.png")));
    }
}
